declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_ZALO_CLIENT_ID: string;
    EXPO_PUBLIC_ZALO_CLIENT_SECRET: string;
    EXPO_PUBLIC_GEMINI_API_KEY: string;
    EXPO_PUBLIC_OPEN_WEATHER_API_KEY: string;
    EXPO_PUBLIC_FIREBASE_API_KEY: string;
    EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
    EXPO_PUBLIC_FIREBASE_PROJECT_ID: string;
    EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET: string;
    EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string;
    EXPO_PUBLIC_FIREBASE_APP_ID: string;
    EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID: string;
    EXPO_PUBLIC_PAYOS_CLIENT_ID: string;
    EXPO_PUBLIC_PAYOS_API_KEY: string;
    EXPO_PUBLIC_PAYOS_CHECKSUM_KEY: string;
    EXPO_PUBLIC_SERVER_URL: string;
    EXPO_PUBLIC_API_URL: string;
  }
}
