export { Login } from './Login'
export { Register } from './Register'
export { FlashScreen } from './FlashScreen'
export { Onboard } from './Onboard'
export { Address } from './Address'
export { UpdateAddress } from './UpdateAddress'
export { AddAddress } from './AddAddress'